#!/bin/bash

appname="program_tester.exe"

if [ -f $appname ]
then
echo -e "old $appname is being destroyed."
rm -rf $appname
echo -e "\033[1;31mold $appname is destroyed.\n"
fi

echo -e "\033[0;97msource file  is being compiled."
g++ main/main.cpp ../sequential_file/machine/machine.cpp machine/similarity_checker.cpp machine/duration_counter.cpp machine/compiler.cpp machine/executor.cpp machine/program_tester.cpp -o $appname

if [ -f $appname ]
then
echo -e "\n\033[32msource file  is compiled successfully."
echo -e "\033[34m$appname is created."
fi